# defining the ard operations
ard-settings:
  "atm-corr" : false
  "cloud-mask" : true
  "stack" : true
  "calibrate" : true
  "clip" : false
  "derived-index" : true

cloud-mask-settings:
  "sen2cor-scl-codes" : [4, 5]
  "fmask-codes" : [1]

output-image-settings:
  "bands" : ["B02", "B03", "B04", "B05", "B06", "B07", "B08", "B8A", "B11", "B12"]
  "vi" : ["ndvi", "ndwi", "ndti", "crc"] 
  "resampling-method" : "near"
