# Config file for Wilmot Cattle Project
# Image Dates: May 2017
# Image Type: S2A-L2A

# list of tiles to process
tile-list:
  tile-1:
    # name of the tile
    "tile-name" : "S2A_MSIL2A_20190521T235251_N0212_R130_T56JMM_20190522T014028.SAFE"

    # defining the ard operations
    ard-settings:
      "atm-corr" : false
      "cloud-mask" : false
      "stack" : true
      "calibrate" : false
      "clip" : true
      "derived-index" : true

    # pixel values in mask to keep (clear pixels)
    cloud-mask-settings:
      #"sen2cor-scl-codes" : [4, 5, 6, 7]
      #"fmask-codes" : [1]

    output-image-settings:
      # bands to stack
      "bands" : ["B02", "B03", "B04", "B05", "B06", "B08", "B11", "B12"]
      # derived indices to calculate
      "vi" : ["ndvi", "vdvi", "bsi"]
      # target spatial reference system - epsg code i. e. 3857
      "t-srs" : False
      # output image resolution
      "resolution" : 10
      # method for resampling bands when resolution changes or reprojection
      "resampling-method" : "cubic"

  tile-2:
    # name of the tile
    "tile-name" : "S2B_MSIL2A_20190506T235259_N0212_R130_T56JMM_20190522T085952.SAFE"

    # defining the ard operations
    ard-settings:
      "atm-corr" : false
      "cloud-mask" : false
      "stack" : true
      "calibrate" : false
      "clip" : true
      "derived-index" : true

    # pixel values in mask to keep (clear pixels)
    cloud-mask-settings:
      #"sen2cor-scl-codes" : [4, 5, 6, 7]
      #"fmask-codes" : [1]

    output-image-settings:
      # bands to stack
      "bands" : ["B02", "B03", "B04", "B05", "B06", "B08", "B11", "B12"]
      # derived indices to calculate
      "vi" : ["ndvi", "vdvi", "bsi"]
      # target spatial reference system - epsg code i. e. 3857
      "t-srs" : False
      # output image resolution
      "resolution" : 10
      # method for resampling bands when resolution changes or reprojection
      "resampling-method" : "cubic"

# mosaic settings
mosaic-settings:
  # build mosaic
  "build-mosaic" : false

# image average settings
average-settings:
  # average images
  "compute-average" : true
  # clip to aoi
  "clip" : true
  # images to include in average
  image-list:
    1: "S2A_MSIL2A_20190521T235251_N0212_R130_T56JMM_20190522T014028.SAFE"
    2: "S2B_MSIL2A_20190506T235259_N0212_R130_T56JMM_20190522T085952.SAFE"
